import type { Metadata } from "next"
import Link from "next/link"
import { format } from "date-fns"
import { GraduationCap, ShieldCheck, ShieldX } from "lucide-react"

import { db, schoolSettings } from "@/db"
import { getReportById } from "@/features/reports/queries"

export const metadata: Metadata = {
  title: "Verify report · Reportly",
  description: "Verify the authenticity of a Reportly report card.",
}

function Detail({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-4 border-b border-border py-3 last:border-0">
      <span className="text-sm text-muted-foreground">{label}</span>
      <span className="text-right text-sm font-medium">{value || "—"}</span>
    </div>
  )
}

export default async function VerifyPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params

  const [report, [settings]] = await Promise.all([
    getReportById(id),
    db.select().from(schoolSettings).limit(1),
  ])

  return (
    <main className="flex min-h-screen items-center justify-center bg-muted/30 px-4 py-12">
      <div className="w-full max-w-md">
        <div className="mb-6 flex items-center justify-center gap-2 text-foreground">
          <span className="flex size-8 items-center justify-center rounded-lg bg-blue-600 text-white">
            <GraduationCap className="size-4.5" />
          </span>
          <span className="text-lg font-semibold tracking-tight">Reportly</span>
        </div>

        <div className="rounded-2xl border border-border bg-background p-6 shadow-sm sm:p-8">
          {report ? (
            <>
              <div className="flex flex-col items-center text-center">
                <span className="flex size-14 items-center justify-center rounded-full bg-emerald-600/10 text-emerald-600">
                  <ShieldCheck className="size-7" />
                </span>
                <h1 className="mt-4 text-xl font-semibold tracking-tight">
                  Authentic report card
                </h1>
                <p className="mt-1 text-sm text-muted-foreground">
                  This report was generated by{" "}
                  {settings?.schoolName || "the school"} and is verified.
                </p>
              </div>

              <div className="mt-6">
                <Detail
                  label="School"
                  value={settings?.schoolName ?? ""}
                />
                <Detail label="Student" value={report.studentName} />
                <Detail label="Admission number" value={report.admissionNumber} />
                <Detail label="Class" value={report.currentClass} />
                <Detail label="Academic year" value={report.academicYear} />
                <Detail label="Term" value={report.term} />
                <Detail
                  label="Generated"
                  value={format(new Date(report.createdAt), "d MMM yyyy")}
                />
              </div>
            </>
          ) : (
            <div className="flex flex-col items-center text-center">
              <span className="flex size-14 items-center justify-center rounded-full bg-destructive/10 text-destructive">
                <ShieldX className="size-7" />
              </span>
              <h1 className="mt-4 text-xl font-semibold tracking-tight">
                Report not found
              </h1>
              <p className="mt-1 text-sm text-muted-foreground">
                We couldn&apos;t verify a report with this code. It may have been
                removed or the link is incorrect.
              </p>
            </div>
          )}
        </div>

        <p className="mt-6 text-center text-xs text-muted-foreground">
          <Link href="/" className="hover:text-foreground">
            Powered by Reportly
          </Link>
        </p>
      </div>
    </main>
  )
}
